# Generated by Django 4.2.4 on 2023-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=200)),
                ('mileage', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
